Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.1"
  config.vm.hostname = "node2.ad.desktopvm.com"
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
  vb.memory = 2048

  config.vm.provision :chef_client do |chef|
    chef.chef_server_url = "https://vagrant-chef.ad.desktopvm.com/organizations/desktopvm"
    chef.validation_key_path = "../.chef/desktopvm-validator.pem"
    chef.validation_client_name = "desktopvm-validator"
    chef.node_name = "node2"
  end
end
end
